export { LoginPage } from './LoginPage';
export { RegisterPage } from './RegisterPage';
export { DashboardPage } from './DashboardPage';
export { StudentDashboard } from './StudentDashboard';
export { TeacherDashboard } from './TeacherDashboard';
export { AdminDashboard } from './AdminDashboard';
export { SettingsPage } from './SettingsPage';
export { CoursesPage } from './CoursesPage';
export { CoursesFormPage } from './CoursesFormPage';
export { CourseDetailPage } from './CourseDetailPage';
export { TasksPage } from './TasksPage';
export { TaskSolvePage } from './TaskSolvePage';
export { SubmissionsPage } from './SubmissionsPage';
export { SubmissionDetailPage } from './SubmissionDetailPage';
export { StudentsPage } from './StudentsPage';
export { ClassesPage } from './ClassesPage';
export {UsersPage} from './UsersPage';
export {RegistrationPendingPage} from './RegistrationPendingPage';
export { ApprovalQueuePage } from './ApprovalQueuePage';
export { TaskFormPage } from './TaskFormPage';
export { TaskDetailPage } from './TaskDetailPage';

